/**
 * Ensure the consumer repo has a local .npmrc with @apex:registry.
 *
 * Projects often gitignore .npmrc (tokens). They should commit .npmrc.template
 * (registry URLs only). This command:
 *   1. Copies .npmrc.template → .npmrc when .npmrc is missing
 *   2. Merges @apex:registry (+ always-auth) into an existing .npmrc
 *   3. Never writes auth tokens
 */
import fs from 'node:fs';
import path from 'node:path';

export const NPMRC_NAME = '.npmrc';
export const NPMRC_TEMPLATE_NAME = '.npmrc.template';

function feedCoords({ org, feed, project } = {}) {
  const resolvedOrg = (org || process.env.AZURE_ARTIFACTS_ORG || 'amergis').trim();
  const resolvedFeed = (feed || process.env.AZURE_ARTIFACTS_FEED || 'apex-skills').trim();
  const resolvedProject = (project || process.env.AZURE_ARTIFACTS_PROJECT || '').trim();
  const registry = resolvedProject
    ? `https://pkgs.dev.azure.com/${resolvedOrg}/${resolvedProject}/_packaging/${resolvedFeed}/npm/registry/`
    : `https://pkgs.dev.azure.com/${resolvedOrg}/_packaging/${resolvedFeed}/npm/registry/`;
  return { org: resolvedOrg, feed: resolvedFeed, project: resolvedProject || null, registry };
}

export function apexRegistryLine(coords) {
  return `@apex:registry=${coords.registry}`;
}

/** True when text already has an @apex:registry assignment. */
export function hasApexRegistry(text) {
  return /^\s*@apex:registry\s*=\s*\S+/m.test(text || '');
}

/**
 * Merge @apex:registry and always-auth into npmrc text. Preserves other lines
 * (e.g. @maxview) and does not touch _authToken lines.
 */
export function mergeApexRegistry(text, coords) {
  const line = apexRegistryLine(coords);
  let body = (text || '').replace(/\r\n?/g, '\n');

  if (hasApexRegistry(body)) {
    body = body.replace(/^\s*@apex:registry\s*=\s*\S+.*$/m, line);
  } else {
    body = body.replace(/\n+$/, '');
    body = body ? `${body}\n${line}\n` : `${line}\n`;
  }

  if (!/^\s*always-auth\s*=\s*true\s*$/im.test(body)) {
    body = body.replace(/\n+$/, '\n') + 'always-auth=true\n';
  }

  if (!body.endsWith('\n')) body += '\n';
  return body;
}

export function defaultMinimalNpmrc(coords) {
  return [
    '# Generated by @apex/skills init-registry — registry URLs only; do not commit tokens.',
    '# Prefer committing .npmrc.template and keeping .npmrc gitignored.',
    apexRegistryLine(coords),
    'always-auth=true',
    '',
  ].join('\n');
}

/**
 * @returns {{
 *   action: 'created-from-template' | 'created-minimal' | 'merged' | 'unchanged',
 *   npmrcPath: string,
 *   templatePath: string | null,
 *   registry: string,
 *   wrote: boolean,
 *   dryRun: boolean,
 *   nextSteps: string[],
 *   contentPreview: string,
 * }}
 */
export function initRegistry(repoRoot, opts = {}) {
  const root = path.resolve(repoRoot);
  const coords = feedCoords(opts);
  const npmrcPath = path.join(root, NPMRC_NAME);
  const templatePath = path.join(root, NPMRC_TEMPLATE_NAME);
  const hasTemplate = fs.existsSync(templatePath);
  const hasNpmrc = fs.existsSync(npmrcPath);

  let action;
  let nextText;

  if (hasNpmrc) {
    const existing = fs.readFileSync(npmrcPath, 'utf8').replace(/\r\n?/g, '\n');
    nextText = mergeApexRegistry(existing, coords);
    action = existing === nextText ? 'unchanged' : 'merged';
  } else if (hasTemplate) {
    const template = fs.readFileSync(templatePath, 'utf8');
    nextText = mergeApexRegistry(template, coords);
    action = 'created-from-template';
  } else {
    nextText = defaultMinimalNpmrc(coords);
    action = 'created-minimal';
  }

  const wrote = action !== 'unchanged' && !opts.dryRun;
  if (wrote) fs.writeFileSync(npmrcPath, nextText, 'utf8');

  const nextSteps = [];
  if (!hasTemplate) {
    nextSteps.push(
      'Tip: commit .npmrc.template (registry URLs only) so teammates can run init-registry after clone.',
    );
  }
  nextSteps.push(
    'Authenticate (token stays local — do not commit tokens; keep .npmrc gitignored if your repo does):',
    '  npx vsts-npm-auth -config .npmrc',
    'Verify:',
    '  npm view @apex/skills version',
    'Then:',
    '  npx @apex/skills doctor',
    '  npx @apex/skills install',
  );

  return {
    action,
    npmrcPath,
    templatePath: hasTemplate ? templatePath : null,
    registry: coords.registry,
    wrote,
    dryRun: Boolean(opts.dryRun),
    nextSteps,
    contentPreview: nextText,
  };
}
