import { randomBytes } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import dotenv from 'dotenv';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(scriptDir, '..', '..');
const envPath = join(repoRoot, '.env');

if (!existsSync(envPath)) {
  console.error(
    'Missing .env. Create it from the team-provided environment file or .env.example first.',
  );
  process.exit(1);
}

const original = readFileSync(envPath, 'utf8');
const parsed = dotenv.parse(original);

if (!parsed.CURSOR_API_KEY?.trim()) {
  console.error(
    'CURSOR_API_KEY must be set in .env before starting the local interactive actor.',
  );
  process.exit(1);
}

const required = new Map([
  ['AI_RUNS_INTERACTIVE_DISPATCH_URL', 'http://127.0.0.1:8080'],
  ['AI_RUNS_INTERACTIVE_GATEWAY', 'true'],
  ['REDIS_URL', 'redis://127.0.0.1:6379'],
  [
    'AI_RUNS_RUNNER_CALLBACK_TOKEN',
    parsed.AI_RUNS_RUNNER_CALLBACK_TOKEN?.trim() || randomBytes(32).toString('hex'),
  ],
]);

const lines = original.replace(/\r\n/g, '\n').split('\n');
const found = new Set();
let changed = false;

for (let index = 0; index < lines.length; index += 1) {
  const match = lines[index].match(/^\s*([A-Z][A-Z0-9_]*)\s*=(.*)$/);
  if (!match || !required.has(match[1])) continue;
  found.add(match[1]);
  if (!match[2].trim()) {
    lines[index] = `${match[1]}=${required.get(match[1])}`;
    changed = true;
  }
}

const missing = [...required.entries()].filter(([key]) => !found.has(key));
if (missing.length > 0) {
  while (lines.length > 0 && lines.at(-1) === '') lines.pop();
  lines.push(
    '',
    '# Local interactive actor (generated by runners/ai-runs-interactive/configure-local.mjs)',
    ...missing.map(([key, value]) => `${key}=${value}`),
    '',
  );
  changed = true;
}

if (changed) {
  writeFileSync(envPath, lines.join('\n'), { encoding: 'utf8', mode: 0o600 });
  console.log('Local interactive actor settings were added to .env.');
  console.log('Restart npm run dev if it was already running.');
} else {
  console.log('Local interactive actor settings are already configured.');
}
