-- Up Migration
ALTER TABLE interviews ADD COLUMN IF NOT EXISTS effort TEXT;
ALTER TABLE adrs ADD COLUMN IF NOT EXISTS effort TEXT;
ALTER TABLE prds ADD COLUMN IF NOT EXISTS effort TEXT;
ALTER TABLE design_docs ADD COLUMN IF NOT EXISTS effort TEXT;
ALTER TABLE design_prototypes ADD COLUMN IF NOT EXISTS effort TEXT;

-- Down Migration
ALTER TABLE interviews DROP COLUMN IF EXISTS effort;
ALTER TABLE adrs DROP COLUMN IF EXISTS effort;
ALTER TABLE prds DROP COLUMN IF EXISTS effort;
ALTER TABLE design_docs DROP COLUMN IF EXISTS effort;
ALTER TABLE design_prototypes DROP COLUMN IF EXISTS effort;
