-- Up Migration
ALTER TABLE project_skill_settings
  ADD COLUMN IF NOT EXISTS interview_effort TEXT,
  ADD COLUMN IF NOT EXISTS prd_effort TEXT,
  ADD COLUMN IF NOT EXISTS adr_effort TEXT,
  ADD COLUMN IF NOT EXISTS design_doc_effort TEXT,
  ADD COLUMN IF NOT EXISTS design_doc_assistant_effort TEXT,
  ADD COLUMN IF NOT EXISTS design_prototype_effort TEXT,
  ADD COLUMN IF NOT EXISTS test_case_effort TEXT,
  ADD COLUMN IF NOT EXISTS design_doc_validation_effort TEXT,
  ADD COLUMN IF NOT EXISTS prd_assistant_effort TEXT,
  ADD COLUMN IF NOT EXISTS prd_validation_effort TEXT,
  ADD COLUMN IF NOT EXISTS development_effort TEXT,
  ADD COLUMN IF NOT EXISTS standup_effort TEXT,
  ADD COLUMN IF NOT EXISTS feature_request_effort TEXT,
  ADD COLUMN IF NOT EXISTS technical_effort TEXT,
  ADD COLUMN IF NOT EXISTS issue_effort TEXT,
  ADD COLUMN IF NOT EXISTS calendar_assistant_effort TEXT,
  ADD COLUMN IF NOT EXISTS load_test_generation_effort TEXT,
  ADD COLUMN IF NOT EXISTS design_module_effort TEXT,
  ADD COLUMN IF NOT EXISTS design_module_scoping_effort TEXT,
  ADD COLUMN IF NOT EXISTS default_effort TEXT;

-- Down Migration
ALTER TABLE project_skill_settings
  DROP COLUMN IF EXISTS interview_effort,
  DROP COLUMN IF EXISTS prd_effort,
  DROP COLUMN IF EXISTS adr_effort,
  DROP COLUMN IF EXISTS design_doc_effort,
  DROP COLUMN IF EXISTS design_doc_assistant_effort,
  DROP COLUMN IF EXISTS design_prototype_effort,
  DROP COLUMN IF EXISTS test_case_effort,
  DROP COLUMN IF EXISTS design_doc_validation_effort,
  DROP COLUMN IF EXISTS prd_assistant_effort,
  DROP COLUMN IF EXISTS prd_validation_effort,
  DROP COLUMN IF EXISTS development_effort,
  DROP COLUMN IF EXISTS standup_effort,
  DROP COLUMN IF EXISTS feature_request_effort,
  DROP COLUMN IF EXISTS technical_effort,
  DROP COLUMN IF EXISTS issue_effort,
  DROP COLUMN IF EXISTS calendar_assistant_effort,
  DROP COLUMN IF EXISTS load_test_generation_effort,
  DROP COLUMN IF EXISTS design_module_effort,
  DROP COLUMN IF EXISTS design_module_scoping_effort,
  DROP COLUMN IF EXISTS default_effort;
