ALTER TABLE interviews ADD COLUMN IF NOT EXISTS model TEXT;
ALTER TABLE prds ADD COLUMN IF NOT EXISTS model TEXT;
ALTER TABLE design_docs ADD COLUMN IF NOT EXISTS model TEXT;
ALTER TABLE design_prototypes ADD COLUMN IF NOT EXISTS model TEXT;
