import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { PhaseSummaryCard } from '../PhaseSummaryCard';
import type { PhaseSummary } from '../../../shared/types/interview';

const mockEdit = jest.fn();
const mockGenerate = jest.fn();
const mockApprove = jest.fn();
const mockAmend = jest.fn();
let summary: PhaseSummary;

jest.mock('../../hooks/useInterviews', () => ({
  usePhaseSummary: () => ({ data: summary, isLoading: false, isError: false }),
  useEditPhaseSummary: () => ({ mutateAsync: mockEdit, isPending: false }),
  useGenerateRequirementsSummary: () => ({
    mutateAsync: mockGenerate,
    isPending: false,
  }),
  useApprovePhaseSummary: () => ({ mutateAsync: mockApprove, isPending: false }),
  useAmendRequirementsSummary: () => ({ mutateAsync: mockAmend, isPending: false }),
}));

describe('PhaseSummaryCard', () => {
  beforeEach(() => {
    jest.clearAllMocks();
    mockEdit.mockResolvedValue({ ok: true });
    mockGenerate.mockResolvedValue({ ...summary, content: 'Generated requirements' });
    mockApprove.mockResolvedValue({ ok: true, isLastConfiguredPhase: false });
    mockAmend.mockResolvedValue({ ok: true, notifiedOwnerId: 'requirements-owner' });
    summary = {
      phase: 'requirements',
      status: 'draft',
      content: 'Draft requirements',
      ownerId: 'requirements-owner',
      ownerName: 'Requirements Owner',
      approvedAt: null,
      locked: false,
      amendable: false,
    };
  });

  it('PBI-003 AC-0 renders an editable draft for its owner and approves saved content', async () => {
    render(
      <PhaseSummaryCard
        interviewId="interview-1"
        phase="requirements"
        currentUserId="requirements-owner"
        technicalOwnerId="technical-owner"
        canManage
      />,
    );

    const textarea = screen.getByTestId('phase-summary-requirements-content');
    fireEvent.change(textarea, { target: { value: 'Reviewed requirements' } });
    fireEvent.click(screen.getByTestId('phase-summary-requirements-approve'));

    await waitFor(() => {
      expect(mockEdit).toHaveBeenCalledWith({
        interviewId: 'interview-1',
        phase: 'requirements',
        content: 'Reviewed requirements',
      });
      expect(mockApprove).toHaveBeenCalledWith({
        interviewId: 'interview-1',
        phase: 'requirements',
      });
    });
  });

  it('PBI-003 AC-1 disables approval until the summary has content', () => {
    summary = { ...summary, content: '' };
    render(
      <PhaseSummaryCard
        interviewId="interview-1"
        phase="requirements"
        currentUserId="requirements-owner"
        technicalOwnerId="technical-owner"
        canManage
      />,
    );

    expect(screen.getByTestId('phase-summary-requirements-approve')).toBeDisabled();
    expect(mockApprove).not.toHaveBeenCalled();
  });

  it('loads the Requirements summary generated by the completed phase skill', async () => {
    summary = { ...summary, content: '' };
    render(
      <PhaseSummaryCard
        interviewId="interview-1"
        phase="requirements"
        currentUserId="requirements-owner"
        technicalOwnerId="technical-owner"
        canManage
      />,
    );

    fireEvent.click(screen.getByTestId('phase-summary-requirements-generate'));

    await waitFor(() => {
      expect(mockGenerate).toHaveBeenCalledWith({ interviewId: 'interview-1' });
    });
  });

  it('keeps in-progress draft edits when imported summary content arrives', () => {
    summary = { ...summary, content: '' };
    const { rerender } = render(
      <PhaseSummaryCard
        interviewId="interview-1"
        phase="requirements"
        currentUserId="requirements-owner"
        technicalOwnerId="technical-owner"
        canManage
      />,
    );

    const textarea = screen.getByTestId('phase-summary-requirements-content');
    fireEvent.change(textarea, { target: { value: 'Owner typed this' } });

    summary = { ...summary, content: 'Imported from skill file' };
    rerender(
      <PhaseSummaryCard
        interviewId="interview-1"
        phase="requirements"
        currentUserId="requirements-owner"
        technicalOwnerId="technical-owner"
        canManage
      />,
    );

    expect(textarea).toHaveValue('Owner typed this');
  });

  it('fills an empty draft when imported summary content arrives', () => {
    summary = { ...summary, content: '' };
    const { rerender } = render(
      <PhaseSummaryCard
        interviewId="interview-1"
        phase="requirements"
        currentUserId="requirements-owner"
        technicalOwnerId="technical-owner"
        canManage
      />,
    );

    summary = { ...summary, content: 'Imported from skill file' };
    rerender(
      <PhaseSummaryCard
        interviewId="interview-1"
        phase="requirements"
        currentUserId="requirements-owner"
        technicalOwnerId="technical-owner"
        canManage
      />,
    );

    expect(screen.getByTestId('phase-summary-requirements-content')).toHaveValue(
      'Imported from skill file',
    );
  });

  it('replaces in-progress draft edits when Generate with AI succeeds', async () => {
    summary = { ...summary, content: '' };
    mockGenerate.mockResolvedValue({ ...summary, content: 'Generated requirements' });
    render(
      <PhaseSummaryCard
        interviewId="interview-1"
        phase="requirements"
        currentUserId="requirements-owner"
        technicalOwnerId="technical-owner"
        canManage
      />,
    );

    const textarea = screen.getByTestId('phase-summary-requirements-content');
    fireEvent.change(textarea, { target: { value: 'Owner typed this' } });
    fireEvent.click(screen.getByTestId('phase-summary-requirements-generate'));

    await waitFor(() => {
      expect(textarea).toHaveValue('Generated requirements');
    });
  });

  it('PBI-003 AC-2/AC-3 renders approved or non-owner summaries read-only', () => {
    summary = {
      ...summary,
      status: 'approved',
      approvedAt: '2026-09-17T12:00:00.000Z',
    };
    const { rerender } = render(
      <PhaseSummaryCard
        interviewId="interview-1"
        phase="requirements"
        currentUserId="requirements-owner"
        technicalOwnerId="technical-owner"
        canManage
      />,
    );

    expect(screen.getByTestId('phase-summary-requirements-approved')).toBeInTheDocument();
    expect(screen.queryByTestId('phase-summary-requirements-content')).not.toBeInTheDocument();
    expect(screen.queryByTestId('phase-summary-requirements-approve')).not.toBeInTheDocument();

    summary = { ...summary, status: 'draft', approvedAt: null };
    rerender(
      <PhaseSummaryCard
        interviewId="interview-1"
        phase="requirements"
        currentUserId="other-user"
        technicalOwnerId="technical-owner"
        canManage
      />,
    );
    expect(screen.getByTestId('phase-summary-requirements-readonly')).toBeInTheDocument();
    expect(screen.queryByTestId('phase-summary-requirements-approve')).not.toBeInTheDocument();
  });

  it('VT-16 / PBI-004 AC-0 exposes Amend only to the Technical owner after unlock', async () => {
    summary = {
      ...summary,
      status: 'approved',
      approvedAt: '2026-09-17T12:00:00.000Z',
      amendable: true,
    };
    render(
      <PhaseSummaryCard
        interviewId="interview-1"
        phase="requirements"
        currentUserId="technical-owner"
        technicalOwnerId="technical-owner"
        canManage
      />,
    );

    fireEvent.click(screen.getByTestId('phase-summary-requirements-amend'));
    const textarea = screen.getByTestId('phase-summary-requirements-amend-content');
    fireEvent.change(textarea, { target: { value: 'Requirements with gap closed' } });
    fireEvent.click(screen.getByTestId('phase-summary-requirements-save-amendment'));

    await waitFor(() => {
      expect(mockAmend).toHaveBeenCalledWith({
        interviewId: 'interview-1',
        content: 'Requirements with gap closed',
      });
    });
  });

  it('PBI-004 AC-1 hides Amend before unlock and for non-Technical owners', () => {
    summary = {
      ...summary,
      status: 'approved',
      approvedAt: '2026-09-17T12:00:00.000Z',
      amendable: false,
    };
    const { rerender } = render(
      <PhaseSummaryCard
        interviewId="interview-1"
        phase="requirements"
        currentUserId="technical-owner"
        technicalOwnerId="technical-owner"
        canManage
      />,
    );
    expect(screen.queryByTestId('phase-summary-requirements-amend')).not.toBeInTheDocument();

    summary = { ...summary, amendable: true };
    rerender(
      <PhaseSummaryCard
        interviewId="interview-1"
        phase="requirements"
        currentUserId="other-user"
        technicalOwnerId="technical-owner"
        canManage
      />,
    );
    expect(screen.queryByTestId('phase-summary-requirements-amend')).not.toBeInTheDocument();
  });
});
